# Generated by Django 2.2.2 on 2019-06-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iwcore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='work',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
